version: '3.8'
services:
  vprodb:
    build:
      context: /root/vprofile-project/Docker-db
    image: krish1739/vprofiledb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      conetext: /root/vprofile-project/Docker-app
    image: krish1739/vprofileapp
    ports:
      - "8080:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build: 
      context: /root/vprofile-project/Docker-web
    image: krish1739/vprofiledb
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}
